import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { cn } from '@/lib/utils';

const RecentReportsTable = ({ reports }) => {
  const { toast } = useToast();

  const handleDownload = (report) => {
    if (report.status !== 'Ready') return;
    toast({
      title: '🚧 Download Action',
      description: `Downloading ${report.name} is not yet implemented.`,
    });
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'Ready':
        return <Badge className="bg-green-500/20 text-green-400 border-green-500/30">✅ Ready</Badge>;
      case 'Generating':
        return <Badge className="bg-yellow-500/20 text-yellow-400 border-yellow-500/30 flex items-center gap-1"><Loader2 className="h-3 w-3 animate-spin" /> Generating</Badge>;
      case 'Failed':
        return <Badge variant="destructive">❌ Failed</Badge>;
      default:
        return <Badge variant="secondary">{status}</Badge>;
    }
  };

  return (
    <Card className="bg-glass-dark border-[#39ff14]/20">
      <CardHeader>
        <CardTitle className="text-white">Recent Reports</CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow className="border-b-[#39ff14]/20 hover:bg-transparent">
                <TableHead>Report Name</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report.id} className="border-b-[#39ff14]/10">
                  <TableCell className="font-medium text-white">{report.name}</TableCell>
                  <TableCell className="text-gray-300">{report.generatedBy}</TableCell>
                  <TableCell className="text-gray-300">{report.date}</TableCell>
                  <TableCell><Badge variant="outline" className="border-[#39ff14]/30 text-[#39ff14]">{report.format}</Badge></TableCell>
                  <TableCell>{getStatusBadge(report.status)}</TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => handleDownload(report)}
                      disabled={report.status !== 'Ready'}
                      className="h-8 w-8 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Download className="h-4 w-4 text-blue-400" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
};

export default RecentReportsTable;